server:
  port: 8090

# 设置Spring-Data-JPA
spring:
  jpa:
    # 指定在Spring容器启动时是否自动建表，默认为false
    generate-ddl: true
    # 指定是否在控制台显示其执行的SQL语句，默认false
    show-sql: true
    # 指定应用重启时是否重新创建更新表
    hibernate:
      ddl-auto: none
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.254.128:3306/test?useUnicode=true&amp;characterEncoding=utf8
    username: root
    password: 123456

logging:
  # 设置日志输出格式
  pattern:
    console: level-%level %msg%n
  level:
    # 控制Spring Boot启动时的日志级别
    root: info
    # 控制hibernate运行时的日志级别
    org.hibernate: info
    # 在show-sql为true时，显示SQL中的动态参数值
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    # 在show-sql为true时，显示SQL查询结果
    org.hibernate.type.descriptor.sql.BasicExtractor: trace
    com.yw.provider: debug